version: "3.9"

services:
  web:
    build: .
    container_name: django_app
    command: python cvproject/manage.py runserver 0.0.0.0:8000
#    I know I know, but well need it in a few tasks
#    command: sh -c "cd cvproject/ &&
#                gunicorn cvproject.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: