# Generated by Django 5.1.7 on 2025-03-28 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=60, null=True)),
                ('lastname', models.CharField(blank=True, max_length=60, null=True)),
                ('skills', models.JSONField()),
                ('projects', models.JSONField()),
                ('bio', models.TextField()),
                ('contacts', models.JSONField()),
            ],
        ),
    ]
