# Generated by Django 5.1.7 on 2025-03-28 20:01

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('http_method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=260)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cvinstance',
            name='contacts',
            field=models.JSONField(validators=[main.models.validate_dict_of_strings]),
        ),
        migrations.AlterField(
            model_name='cvinstance',
            name='projects',
            field=models.JSONField(validators=[main.models.validate_list_of_strings]),
        ),
        migrations.AlterField(
            model_name='cvinstance',
            name='skills',
            field=models.JSONField(validators=[main.models.validate_list_of_strings]),
        ),
    ]
